export const ACTION_SHEET_DURATION = 0.2; // ActionSheet 动画时长（秒）
export const TABBAR_BG_ALPHA = 0.3; // 底部导航栏背景透明度（浅色）
export const TABBAR_BG_ALPHA_DARK = 0.3; // 底部导航栏背景透明度（深色）
export const TABBAR_INDICATOR_DURATION = 0.42; // 选中指示条动画时长（秒）
export const TABBAR_INDICATOR_EASING = 'cubic-bezier(0.2, 0.9, 0.15, 1.2)'; // 指示条动画缓动
export const NAV_BG_ALPHA = 0.55; // 顶部导航栏背景透明度（浅色）
export const NAV_BG_ALPHA_DARK = 0.4; // 顶部导航栏背景透明度（深色）
export const NAV_ICON_BG_ALPHA = 0.55; // 顶部导航按钮背景透明度（浅色）
export const NAV_ICON_BG_ALPHA_DARK = 0.5; // 顶部导航按钮背景透明度（深色）
export const MOBILE_GAP = 16; // 移动端页面通用间距
export const MOBILE_CARD_RADIUS = 20; // 卡片圆角
export const MOBILE_CARD_PADDING = 16; // 卡片内边距
export const HERO_PRIMARY_ALPHA = 0.18; // Hero 主色光晕透明度（浅色）
export const HERO_ACCENT_ALPHA = 0.12; // Hero 辅色光晕透明度（浅色）
export const HERO_BORDER_ALPHA = 0.25; // Hero 边框透明度（浅色）
export const HERO_PRIMARY_ALPHA_DARK = 0.22; // Hero 主色光晕透明度（深色）
export const HERO_ACCENT_ALPHA_DARK = 0.16; // Hero 辅色光晕透明度（深色）
export const HERO_BORDER_ALPHA_DARK = 0.28; // Hero 边框透明度（深色）
export const PANEL_TINT_ALPHA = 0.06; // 面板背景微染色透明度（浅色）
export const PANEL_TINT_ALPHA_DARK = 0.12; // 面板背景微染色透明度（深色）
export const PANEL_GLOW_ALPHA = 0.18; // 面板内发光透明度
export const METRIC_TINT_ALPHA = 0.05; // 指标卡背景微染色透明度（浅色）
export const METRIC_TINT_ALPHA_DARK = 0.12; // 指标卡背景微染色透明度（深色）
export const CARD_SHADOW_ALPHA = 0.12; // 卡片投影透明度（浅色）
export const CARD_SHADOW_ALPHA_DARK = 0.45; // 卡片投影透明度（深色）
export const CARD_SHADOW_SOFT_ALPHA = 0.08; // 卡片柔和投影透明度（浅色）
export const CARD_SHADOW_SOFT_ALPHA_DARK = 0.35; // 卡片柔和投影透明度（深色）
export const NAV_BLUR = 18; // 顶部导航栏毛玻璃模糊半径
export const NAV_SHADOW_ALPHA = 0.08; // 顶部导航栏阴影透明度（浅色）
export const NAV_SHADOW_ALPHA_DARK = 0.35; // 顶部导航栏阴影透明度（深色）
export const NAV_ICON_SHADOW_ALPHA = 0.12; // 顶部导航按钮阴影透明度
export const NAV_ICON_BLUR = 12; // 顶部导航按钮毛玻璃模糊半径
export const TABBAR_BLUR = 16; // 底部导航栏毛玻璃模糊半径
export const TABBAR_RADIUS = 999; // 底部导航栏整体圆角（胶囊形）
export const TABBAR_MARGIN_BOTTOM = 6; // 底部导航栏距安全区的额外外边距
export const TABBAR_GUTTER = 50; // 底部导航栏左右留白（控制整体宽度）
export const TABBAR_MAX_WIDTH = 480; // 底部导航栏最大宽度
export const TABBAR_PADDING_X = 8; // 底部导航栏横向内边距
export const TABBAR_PADDING_Y = 2; // 底部导航栏纵向内边距
export const TABBAR_SHADOW_ALPHA = 0.18; // 底部导航栏阴影透明度（浅色）
export const TABBAR_SHADOW_ALPHA_DARK = 0.55; // 底部导航栏阴影透明度（深色）
export const TABBAR_INDICATOR_INSET = 8; // 指示条上下内缩（决定选中高度）
export const TABBAR_INDICATOR_RADIUS = 999; // 指示条圆角（胶囊形）
export const MOBILE_TABBAR_BOTTOM = false; // 是否默认启用底部导航栏
